Remove the frontend
doner-kebard/card-game-backend pull request #2
Opened 2018-10-01 16:28 UTC by kenan-rhoton

**Description**

This Pull Request removes all the frontend artifacts that are left over from the migration

**Details**

Checklist for things that need to be done:

- [x] Remove the frontend stuff
- [ ] Modify .travis.yml
- [ ] Modify CONTRIBUTING stuff
- [ ] Remove Codacy stuff (that was just being used in frontend)
- [ ] Restructure things like the configs correctly
- [ ] Make sure it actually works...

**Hotspots**

EVERYTHING

**Checklist for contribution requirements**

- [ ] The tests pass
- [ ] The code has tests
- [ ] The tests are well-designed
- [ ] The code is readable
- [ ] The code is well-organized
- [ ] Any rule changed or included is also on the Manual

2018-10-01 21:40 UTC, kenan-rhoton commented
Ok, this is ready for review! @Masclins

2018-10-02 06:09 UTC, Masclins requested changes
As I understand it, we no longer need `configs/config.yml`.
Why would we keep it?

2018-10-02 06:19 UTC, kenan-rhoton commented
I was thinking of that earlier, we can just hard-code it, does that seem fine?

2018-10-02 07:43 UTC, Masclins approved these changes

2018-10-02 07:43 UTC, merged